### ISSUE TITLE
library(sha): Links to Wikipedia are incorrectly rendered

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-clib#12]
Please check out:

http://eu.swi-prolog.org/pldoc/man?section=sha

It contains two incorrectly rendered links to Wikipedia:

<pre>
Quoting [Wikipedia]http://en.wikipedia.org/wiki/SHA-1: ``The SHA (Secure Hash Algorithm) 
</pre>

and:

<pre>
Quoting [Wikipedia]http://en.wikipedia.org/wiki/HMAC: ``A keyed-hash message 
</pre>

**Comment by JanWielemaker** [comment]
Fixed
