### ISSUE TITLE
`uri_is_global/1` fails for some global URIs

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/packages-clib#18]
[`uri_is_global/2`](http://www.swi-prolog.org/pldoc/doc_for?object=uri_is_global/1) does not have the behavior it should have according to its documentation:

``` prolog
?- uri_components('a:b', Comps), uri_data(scheme, Comps, Scheme), nonvar(Scheme).
Comps = uri_components(a, _G2145, b, _G2147, _G2148),
Scheme = a.
```

The same does not work with `uri_is_global/1`:

```prolog
?- uri_is_global('a:b').
false.
```

**Comment by JanWielemaker** [comment]
Updated docs with 36842a8e314241cf9323d5c88a944c1d8b699595.  Was modified in aa91d6c642d7d8c928eac84d3c320dceb16f6799.
