### ISSUE TITLE
Misleading error message for rlimit/3

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/packages-clib#19]
The following error message is a bit misleading:

```prolog
?- [library(rlimit)].
?- rlimit(nofile, _, 5000).
ERROR: error in system call (Invalid argument)
ERROR: In:
ERROR:    [8] clib_rlimit:rlimit(nofile,1024,5000)
ERROR:    [7] <user>
```

The problem is not that the argument is invalid, but that the OS has a lower hard limit.  A better exception would be `resource_error/1`.

**Comment by JanWielemaker** [comment]
There is little one can reasonably do.  The underlying system call says `EINVAL`, which can mean a lot of things.  We'd have to look around ourselves which is the most likely cause.  I think that is way above what one can expect for this rather obscure predicate.   And then, should it be a resource_error?  A permission_error also makes sense ...

**Comment by wouterbeek** [comment]
Fair points.  The predicate may be somewhat obscure, but it is needed if one uses the RocksDB library.
