### ISSUE TITLE
time.c tries to join a detached thread

### ISSUE THREAD

**Issue by thetrime** [SWI-Prolog/packages-clib#25]
The scheduler thread is created detached: 
```
    pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_DETACHED);
    pthread_attr_setstacksize(&attr, 8192);
    rc = pthread_create(&scheduler, &attr, alarm_loop, NULL);
```
but in cleanup() we call
```
    pthread_join(scheduler, NULL);
```

According to pthread_join(3) [1]

> The behavior is undefined if the value specified by the thread argument to pthread_join() does not refer to a joinable thread.

This has probably gone unnoticed for so long because undefined doesn't *necessarily* mean _crash_. However, in Alpine Linux, it certainly seems to!

I'm not sure what the intention was here - but either the thread should not be created detached, or we shouldn't bother trying to join it on cleanup

[1] [http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_join.html](url)

**Comment by JanWielemaker** [comment]
Thank for noting.  Considering we try to get rid of most threads as shutdown, I think creating it not detached is cleaner.  I do not have a strong opinion though.   Pushed a fix.
